version: 0.0.{build}

configuration: Release

before_build:
 - nuget restore

build_script:
 - choco install "sonarscanner-msbuild-net46" -y
 - SonarScanner.MSBuild.exe begin /k:"dotJEM_SonarQube-CSharp-Repros" /d:"sonar.host.url=https://sonarcloud.io" /o:"dotjem" /d:sonar.login="883c2affa06385c928c3d022c0852888e2e119d2"
 - msbuild /verbosity:quiet "SonarRepros\SonarRepros.sln"
 - SonarScanner.MSBuild.exe end /d:sonar.login="883c2affa06385c928c3d022c0852888e2e119d2"